ASPTime/Models/TimerViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ASPTime.Models
{
    public class TimerViewModel
    {
        public List<Category> Categories { get; set; }
    }
}

ASPTime/Controllers/AjaxController.cs
using ASPTime.Models;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Newtonsoft.Json;

namespace ASPTime.Controllers
{
    public class AjaxController : Controller
    {
        [HttpPost]
        public async Task<ActionResult> ChangeCategoryName(string oldName, string newName)
        {
            var identityUserId = User.Identity.GetUserId();
            using (var context = new ApplicationDbContext())
            {
                try
                {
                    var category = context.Categories.Where(o => o.Name == oldName && o.User.Id == identityUserId).First();
                    category.Name = newName;
                    await context.SaveChangesAsync();
                }
                catch (Exception ex)
                {
                    Debug.WriteLine("Ошибка изменения названия категории " + ex.Source + " " + ex.Message);
                    return Json(new { Success = false });
                }
            }
            return Json(new { Success = true, Name = newName }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public async Task<ActionResult> AddCategory(string categoryName)
        {
            if(categoryName == "" || categoryName == null)
            {
                return Json(new { Success = false, Message = "Ошибка добавления категории" });
            }
            var identityUserId = User.Identity.GetUserId();
            int categoryId = 0;
            using (var context = new ApplicationDbContext())
            {
                
                ApplicationUser user = new ApplicationUser();
                try
                {
                    user = context.Users.Where(o => o.Id == identityUserId).First();
                }
                catch(Exception ex)
                {
                    Debug.WriteLine("Пользователь не найден " + ex.Source + " " + ex.Message);
                    return Json(new { Success = false, Message = "Пользователь не найден" });
                }
                
                var alreadyExist = context.Categories.Where(o => o.Name == categoryName && o.User.Id == identityUserId).FirstOrDefault();
                if(alreadyExist == null)
                {
                    context.Categories.Add(new Category { Name = categoryName, User = user });
                    await context.SaveChangesAsync();
                    categoryId = context.Categories.Where(o => o.Name == categoryName && o.User.Id == identityUserId).Select(o => o.Id).FirstOrDefault();
                }
                else
                {
                    Debug.WriteLine("Ошибка добавления категории");
                    return Json(new { Success = false, Message = "Ошибка добавления категории" });
                }
            }
            return Json(new { Success = true, Name = categoryName, CategoryId = categoryId }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public async Task<ActionResult> DeleteCategory(string categoryName)
        {
            if (categoryName == "" || categoryName == null)
            {
                return Json(new { Success = false, Message = "Ошибка Удаления категории" });
            }
            var identityUserId = User.Identity.GetUserId();
            int categoryId = 0;
            using (var context = new ApplicationDbContext())
            {
                ApplicationUser user = new ApplicationUser();
                try
                {
                    user = context.Users.Where(o => o.Id == identityUserId).First();
                }
                catch (Exception ex)
                {
                    Debug.WriteLine("Пользователь не найден " + ex.Source + " " + ex.Message);
                    return Json(new { Success = false, Message = "Пользователь не найден" });
                }
                var alreadyExist = context.Categories.Where(o => o.Name == categoryName && o.User.Id == identityUserId).FirstOrDefault();

                if(alreadyExist != null)
                {
                    categoryId = context.Categories.Where(o => o.Name == categoryName && o.User.Id == identityUserId).Select(o => o.Id).FirstOrDefault();
                    context.Categories.Remove(alreadyExist);
                    await context.SaveChangesAsync();
                }
                else
                {
                    Debug.WriteLine("Ошибка удаления категории");
                    return Json(new { Success = false, Message = "Ошибка ошибка удаления категории" });
                }
                return Json(new { Success = true, CategoryId = categoryId }, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        public async Task<ActionResult> SaveTimeResult(string categoryName, int time)
        {
            if(categoryName == "" || categoryName == null || time == 0)
            {
                return Json(new { Success = false, Message = "Ошибка сохранения результата" });
            }
            var identityUserId = User.Identity.GetUserId();
            Category category = new Category();
            ApplicationUser user = new ApplicationUser();
            using (var context = new ApplicationDbContext())
            {
                try
                {
                    category = context.Categories.Where(o => o.Name == categoryName && o.User.Id == identityUserId).First();
                }
                catch(Exception ex)
                {
                    Debug.WriteLine("Категория не найдена " + ex.Source + " " + ex.Message);
                    return Json(new { Success = false, Message = "Категория не найдена" });
                }
                try
                {
                    user = context.Users.Where(o => o.Id == identityUserId).First();
                }
                catch(Exception ex)
                {
                    Debug.WriteLine("Пользователь не найден " + ex.Source + " " + ex.Message);
                    return Json(new { Success = false, Message = "Пользователь не найдены" });
                }
                try
                {
                    context.Times.Add(new TimeData
                    {
                        Date = DateTime.Now,
                        Time = time,
                        Category = category,
                        User = user
                    });
                    await context.SaveChangesAsync();
                }
                catch(Exception ex)
                {
                    Debug.WriteLine("Ошибка сохранения " + ex.Source + " " + ex.Message);
                    return Json(new { Success = false, Message = "Ошибка сохранения" });
                }
                return Json(new { Success = true }, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        public async Task<ActionResult> SaveTimeResultFromInterval(string categoryName, int time, string dateIso)
        {
            if (categoryName == "" || categoryName == null || time == 0 || dateIso == "" || dateIso == null)
            {
                return Json(new { Success = false, Message = "Ошибка сохранения результата" });
            }
            var identityUserId = User.Identity.GetUserId();
            Category category = new Category();
            ApplicationUser user = new ApplicationUser();
            using (var context = new ApplicationDbContext())
            {
                try
                {
                    category = context.Categories.Where(o => o.Name == categoryName && o.User.Id == identityUserId).First();
                }
                catch (Exception ex)
                {
                    Debug.WriteLine("Категория не найдена " + ex.Source + " " + ex.Message);
                    return Json(new { Success = false, Message = "Категория не найдена" });
                }
                try
                {
                    user = context.Users.Where(o => o.Id == identityUserId).First();
                }
                catch (Exception ex)
                {
                    Debug.WriteLine("Пользователь не найден " + ex.Source + " " + ex.Message);
                    return Json(new { Success = false, Message = "Пользователь не найдены" });
                }
                try
                {
                    context.Times.Add(new TimeData
                    {
                        Date = DateTime.Parse(dateIso),
                        Time = time,
                        Category = category,
                        User = user
                    });
                    await context.SaveChangesAsync();
                }
                catch (Exception ex)
                {
                    Debug.WriteLine("Ошибка сохранения " + ex.Source + " " + ex.Message);
                    return Json(new { Success = false, Message = "Ошибка сохранения" });
                }
                return Json(new { Success = true }, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult GetStatisticsForToday()
        {
            var identityUserId = User.Identity.GetUserId();
            List<Category> categories = new List<Category>();
            Chart chart = new Chart();
            Chart chart1 = new Chart();
            Chart chart2 = new Chart();
            Chart chart3 = new Chart();
            List<ChartPieValue> chartPieValues = new List<ChartPieValue>();
            ChartDataAdapter adapter = new ChartDataAdapter();
            using (var context = new ApplicationDbContext())
            {
                try
                {
                    categories = context.Users.Where(o => o.Id == identityUserId)
                        .Select(o => o.UserCategories).First();
                }
                catch (Exception ex)
                {

ASPTime/Controllers/HomeController.cs
using ASPTime.Models;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace ASPTime.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            if (Request.IsAuthenticated)
                return RedirectToAction("Timer");
            else
                return RedirectToAction("About");     
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public async Task<ActionResult> Timer()
        {
            var viewModel = new TimerViewModel();
            var identityUserId = User.Identity.GetUserId();
            using (var context = new ApplicationDbContext())
            {
                try
                {
                    viewModel.Categories = await context.Categories.Where(o => o.User.Id == identityUserId).ToListAsync();
                }
                catch (Exception ex)
                {
                    Debug.WriteLine("Ошибка поиска категорий у пользователя: " + ex.Source + " " + ex.Message);
                }

            }
            return View(viewModel);
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

ASPTime/Views/Home/About.cshtml
@using Microsoft.AspNet.Identity


@{
    ViewBag.Title = "About";
}


<div class="container-fluid main-block d-flex align-items-center justify-content-center">
    <div class="row">
        <div class="col-lg-12">
            <div class="d-flex justify-content-center">
                <div class="col-4">
                    <div class="block">
                        <img src="~/Content/img/clock.png" class="img-thumbnail" />
                    </div>
                </div>
            </div>
            <h4 class="text-center mt-4"><strong>Зафиксируйте свою активность</strong></h4>
        </div>
    </div>
</div>
<div class="white container-fluid main-block d-flex align-items-center justify-content-center">
    <div class="row">
        <div class="col-lg-12">
            <div class="d-flex justify-content-center">
                <div class="col-4">
                    <div class="block">
                        <img src="~/Content/img/statistics.png" class="img-thumbnail" />
                    </div>
                </div>
            </div>
            <h4 class="text-center mt-4"><strong>Оцените результаты и станьте лучше</strong></h4>
        </div>
    </div>
</div>
<div class="black container-fluid main-block d-flex align-items-center justify-content-center">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="text-center"><strong>Контролируйте<br />свое время иначе!</strong></h1>
            <div class="d-flex justify-content-center mt-3">
                <a class="ref-button" href="@Url.Action("Register", "Account")"><h1 class="text-center">Начать</h1></a>
            </div>
        </div>
    </div>
    
</div>

@section Style {
    <link href="https://fonts.googleapis.com/css?family=Quicksand" rel="stylesheet">
    <link href="~/Content/homeAbout.css" rel="stylesheet" />
}

ASPTime/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

ASPTime/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}


<h1>@ViewBag.Title</h1>

ASPTime/Views/Home/Timer.cshtml
@using Microsoft.AspNet.Identity

@{
    ViewBag.Title = "Timer";
}

@model ASPTime.Models.TimerViewModel

<div class="container main-block d-flex align-items-center justify-content-center">
    <div class="">
        <div class="container d-flex justify-content-center">
            <h1 class="upper-text mt-5">It's time <br> To begin <i class="far fa-clock"></i></h1>
        </div>
        <div class="container d-flex justify-content-center mt-3">
            <h1 class="clock">
                00:00:00
            </h1>
        </div>
        <div class="container d-flex justify-content-center mt-3">
            <button type="button" class="button-style">
                start
            </button>
            <button type="button" class="button-style-add" data-toggle="modal" data-target="#addTimeModal">
                <h3 class="text-center align-middle"><i class="fas fa-plus-circle"></i></h3>
            </button>
        </div>
    </div>
</div>

<div class="modal fade" id="saveModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle"
     aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Сохранение результата</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-sm-12">
                        <h4 id="body-text"></h4>
                    </div>
                    <div class="col-sm-12 mt-3">
                        <h5>Чем вы занимались?</h5>
                    </div>
                    <div class="col-sm-12">
                        <select class="form-control" id="saveResultSelect">
                            <option>Choose...</option>
                            @foreach (var categoty in Model.Categories)
                            {
                                <option>@categoty.Name</option>
                            }
                        </select>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" id="saveTimeBtn">Сохранить</button>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="addTimeModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle"
     aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Добавить запись</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-12">
                        <div class="alert alert-danger d-none" role="alert">
                            <h4 class="alert-heading">Ошибка</h4>
                        </div>
                    </div>
                    <div class="col-sm-12">
                        <select class="form-control" id="saveTimeSelect">
                            <option>Choose...</option>
                            @foreach (var categoty in Model.Categories)
                            {
                                <option>@categoty.Name</option>
                            }
                        </select>
                    </div>
                    <div class="col-12 col-sm-6 mt-3">
                        <input required type="text" class="text-center form-control datetimepicker-input"
                               id="timepicker1" />
                    </div>
                    <div class="col-12 col-sm-6 mt-3">
                        <input required type="text" class="text-center form-control datetimepicker-input"
                               id="timepicker2" />
                    </div>
                    <div class="col-12 mt-3">
                        <h4 class="text-center" id="timeinterval"></h4>
                    </div>
                    <div class="col-sm-12 mt-3 d-flex justify-content-center">
                        <div class="datepicker-here" id="datepicker"></div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" id="addTimeBtn" class="btn btn-primary" data-dismiss="alert">Добавить</button>
            </div>
        </div>
    </div>
</div>

@section Style{
    <link href="https://fonts.googleapis.com/css?family=Quicksand" rel="stylesheet">
    <link href="~/Content/homeTimer.css" rel="stylesheet" />
    <link href="~/Content/timedropper.css" rel="stylesheet" />
    <link href="~/Content/datepicker.css" rel="stylesheet" />
}

@section Scripts{
    <script src="~/Scripts/moment.js"></script>
    <script src="~/Scripts/easytimer.js"></script>
    <script src="~/Scripts/timedropper.js"></script>
    <script src="~/Scripts/datepicker.js"></script>
    <script src="~/Scripts/homeTimer.js"></script>
    <script>

        function ajaxSaveTimeResult(categoryName, timeResult, dateIso) {
            $.ajax({
                url: '@Url.Action("SaveTimeResultFromInterval","Ajax")',
                type: 'POST',
                data: { categoryName: categoryName, time: timeResult, dateIso: dateIso },
                context: this,
                async: true,
                success: function (data) {
                    if (data.Success) {
                        $('#addTimeModal').modal('hide');
                    }
                    else {
                        alert(data.Message);
                    }
                }
            });
        }
        $('button#saveTimeBtn').click(function (e) {
            $.ajax({
                url: '@Url.Action("SaveTimeResult","Ajax")',
                type: 'POST',
                data: { categoryName: $("select#saveResultSelect option:selected").val(), time: toSeconds(timeArray[0], timeArray[1], timeArray[2]) },
                context: this,
                async: true,
                success: function (data) {
                    if (data.Success) {
                        $('#saveModal').modal('hide');
                    }
                    else {
                        alert(data.Message);
                    }
                }
            });
        });

    </script>
}